skills = [
    'JavaScript', # programming language (27)
    'Python',
    'Java',
    'C#',
    'C++',
    'TypeScript',
    'Ruby',
    'Swift',
    ' Go ',
    'Kotlin',
    'PHP',
    ' R ',
    'Objective-C',
    'Rust',
    'Scala',
    'Shell',
    'Perl',
    'Groovy',
    'Lua',
    'Haskell',
    'MATLAB',
    'Julia',
    'Dart',
    'PowerShell',
    'Elixir',
    'HTML',
    'CSS,', # Frameworks (25)
    'React',
    'Angular',
    'Vue.js',
    'Node.js',
    'Django',
    'Ruby on Rails',
    'Spring Boot',
    'ASP.NET',
    'Express.js',
    'Flask',
    'Laravel',
    'Symfony',
    'ASP.NET Core',
    'ASP.NET MVC',
    'Hibernate',
    'Flutter',
    'Ionic',
    'React Native',
    'Xamarin',
    'TensorFlow',
    'PyTorch',
    'Keras',
    'Scikit-learn',
    'Apache Spark',
    'jQuery', # databases (25)
    'MySQL',
    'PostgreSQL',
    'Microsoft SQL Server',
    'Oracle Database',
    'MongoDB',
    'Redis',
    'SQLite',
    'Amazon RDS',
    'Google Cloud SQL',
    'Azure SQL Database',
    'Firebase',
    'Cassandra',
    'Elasticsearch',
    'Couchbase',
    'DynamoDB',
    'Neo4j',
    'MariaDB',
    'IBM DB2',
    'Memcached',
    'Apache HBase',
    'Teradata',
    'InfluxDB',
    'RethinkDB',
    'RavenDB',
    'ArangoDB', # libraries (25)
    'requests',
    'NumPy',
    'Pandas',
    'matplotlib',
    'scikit-learn',
    'TensorFlow',
    'Keras',
    'PyTorch',
    'Django',
    'Flask',
    'React',
    'Angular',
    'Vue.js',
    'Express.js',
    'jQuery',
    'Bootstrap',
    'Selenium',
    'BeautifulSoup',
    'NLTK',
    'PySpark',
    'OpenCV',
    'Gensim',
    'SQLAlchemy',
    'pytest',
    'unittest',
    'pytest-django', # cloud (25)
    'Amazon Web Services (AWS)',
    'Microsoft Azure',
    'Google Cloud Platform (GCP)',
    'IBM Cloud',
    'Oracle Cloud Infrastructure',
    'Alibaba Cloud',
    'Salesforce Cloud',
    'DigitalOcean',
    'VMware Cloud',
    'Red Hat OpenShift',
    'Heroku',
    'Rackspace',
    'SAP Cloud Platform',
    'Adobe Experience Cloud',
    'Cisco Cloud',
    'HP Helion',
    'Kubernetes',
    'Docker Swarm',
    'OpenStack',
    'Apache Mesos',
    'Pivotal Cloud Foundry',
    'HashiCorp Nomad',
    'VMware Tanzu',
    'Citrix Cloud',
    'Zoho Cloud', # tools (31)
    'Git',
    'Docker',
    'Kubernetes',
    'Jenkins',
    'Ansible',
    'Terraform',
    'Linux',
    'Windows',
    'Visual Studio Code',
    'IntelliJ IDEA',
    'Eclipse',
    'Postman',
    'Swagger',
    'Jira',
    'Confluence',
    'Slack',
    'Trello',
    'GitHub',
    'Bitbucket',
    'Jupyter Notebook',
    'Tableau',
    'Power BI',
    'Splunk',
    'Elasticsearch',
    'Kibana',
    'Prometheus', 
    'Excel',
    'Word',
    ' SAS ',
    'SAP',
    'SSIS',
    'PowerPoint'
]